server:
  port: 8084
spring:
  application:
    name: cloud-gateway-api
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true  #开启网关拉取nacos的服务
      routes: #数组形式
        - id: cloud-video-service  #路由唯一标识
          #uri: http://127.0.0.1:8083  #想要转发到的地址
          uri: lb://cloud-video-service  #想要转发到的地址
          order: 1 #优先级，数字越小优先级越高
          predicates: #断言 配置哪个路径才转发
            - Path=/video-server/**
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1  #去掉第一层前缀​
#访问路径 http://localhost:8084/video-server/video/testGetVideo
#转发路径 http://localhost:8083/video-server/video/testGetVideo
#需要过滤器去掉前面第一层