server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    #保存特殊字符的配置
    tomcat:
      init-s-q-l: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 36000ms
    database: 0
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数默认8（使用负值表示没有限制）
        max-wait: -1ms #连接池最大阻塞等待时间默认-1（使用负值表示没有限制）
        max-idle: 8 #连接池中最大空闲连接 默认8
        min-idle: 0 #连接池中的最小空闲连接 默认0
