server:
  port: 8081
spring:
  application:
    name: cloud-order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 9000
#控制台输出sql、下划线转驼峰video
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#服务请求路径
service:
  url:
    video: http://cloud-video-service
#开启fegin对sentinel的支持
feign:
  sentinel:
    enabled: true
#修改负载均衡策略为随机策略（默认轮询策略）  一般使用默认不建议修改
#第一行为服务端serviceid
#cloud-video-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule