#server:
#  port: 8081
#spring:
#  application:
#    name: cloud-order-service
#  zipkin:
#    base-url: http://127.0.0.1:9411/ #zipkin地址
#    discovery-client-enabled: false  #不用开启服务发现
#  #默认为0.1，即10%，这里配置1，是记录全部的sleuth信息，是为了收集到更多的数据（仅供测试用）。
#  #在分布式系统中，过于频繁的采样会影响系统性能，所以这里配置需要采用一个合适的值。
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8080
#        port: 9000
##控制台输出sql、下划线转驼峰video
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
##服务请求路径
#service:
#  url:
#    video: http://cloud-video-service
##开启fegin对sentinel的支持
#feign:
#  sentinel:
#    enabled: true
#
##修改负载均衡策略为随机策略（默认轮询策略）  一般使用默认不建议修改
##第一行为服务端serviceid
#cloud-video-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule